version: "3"

services:
  # mongodb:
  #   image: mongo
  #   container_name: my-mongodb-container
  #   restart: always
  #   networks:
  #     - mynetwork
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: maes
  #     MONGO_INITDB_ROOT_PASSWORD: maes
  #   ports:
  #     - "27017:27017"

  redis:
    image: redis
    container_name: my-redis-container
    restart: always
    networks:
      - mynetwork
    ports:
      - "6379:6379"

networks:
  mynetwork:
    driver: bridge
