version: "3"

services:
  redis:
    image: redis
    container_name: my-redis-container
    restart: always
    networks:
      - mynetwork
    ports:
      - "6379:6379"

networks:
  mynetwork:
    driver: bridge
